name: Cleanup Inactive Cloud Run Revisions

on:
  schedule:
    - cron: '0 3 1 * *' # Runs at 03:00 on the 1st of every month
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to clean up'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - dev
          - prod

jobs:
  cleanup-dev:
    name: Dev
    if: github.event_name == 'schedule' || github.event.inputs.environment == 'all' || github.event.inputs.environment == 'dev'
    uses: ./.github/workflows/cleanup-env.yml
    with:
      environment: dev
    secrets: inherit

  cleanup-prod:
    name: Prod
    if: github.event_name == 'schedule' || github.event.inputs.environment == 'all' || github.event.inputs.environment == 'prod'
    uses: ./.github/workflows/cleanup-env.yml
    with:
      environment: prod
    secrets: inherit