name: Cleanup Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Delete Old Revisions
        run: |
          REGION=${{ vars.GCP_REGION }}
          CUTOFF_DATE=$(date -u -d "30 days ago" +"%Y-%m-%dT%H:%M:%SZ")

          for SERVICE in $(gcloud run services list --region="$REGION" --format="value(metadata.name)"); do
            echo "Processing service: $SERVICE"
            for REV in $(gcloud run revisions list --service="$SERVICE" --region="$REGION" --filter="metadata.creationTimestamp < '$CUTOFF_DATE' AND active != true" --format="value(metadata.name)"); do
              echo "Deleting $REV"
              gcloud run revisions delete "$REV" --region="$REGION" --quiet || true
            done
          done
